// convpng v6.8
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __logo_gfx__
#define __logo_gfx__
#include <stdint.h>

#define logo_gfx_transparent_color_index 0

#define water_full_width 27
#define water_full_height 29
#define water_full_size 785
extern uint8_t water_full_data[785];
#define water_full ((gfx_sprite_t*)water_full_data)
#define water_surface_width 27
#define water_surface_height 29
#define water_surface_size 785
extern uint8_t water_surface_data[785];
#define water_surface ((gfx_sprite_t*)water_surface_data)
#define lava_full_width 27
#define lava_full_height 29
#define lava_full_size 785
extern uint8_t lava_full_data[785];
#define lava_full ((gfx_sprite_t*)lava_full_data)
#define lava_surface_width 27
#define lava_surface_height 29
#define lava_surface_size 785
extern uint8_t lava_surface_data[785];
#define lava_surface ((gfx_sprite_t*)lava_surface_data)
#define glass_block_width 27
#define glass_block_height 29
#define glass_block_size 785
extern uint8_t glass_block_data[785];
#define glass_block ((gfx_sprite_t*)glass_block_data)
#define glass_pane_west_to_east_width 27
#define glass_pane_west_to_east_height 29
#define glass_pane_west_to_east_size 785
extern uint8_t glass_pane_west_to_east_data[785];
#define glass_pane_west_to_east ((gfx_sprite_t*)glass_pane_west_to_east_data)
#define glass_pane_south_to_north_width 27
#define glass_pane_south_to_north_height 29
#define glass_pane_south_to_north_size 785
extern uint8_t glass_pane_south_to_north_data[785];
#define glass_pane_south_to_north ((gfx_sprite_t*)glass_pane_south_to_north_data)
#define oak_leaves_width 27
#define oak_leaves_height 29
#define oak_leaves_size 785
extern uint8_t oak_leaves_data[785];
#define oak_leaves ((gfx_sprite_t*)oak_leaves_data)
#define stone_brick_stairs_east_width 27
#define stone_brick_stairs_east_height 29
#define stone_brick_stairs_east_size 785
extern uint8_t stone_brick_stairs_east_data[785];
#define stone_brick_stairs_east ((gfx_sprite_t*)stone_brick_stairs_east_data)
#define stone_brick_stairs_east_2_width 27
#define stone_brick_stairs_east_2_height 29
#define stone_brick_stairs_east_2_size 785
extern uint8_t stone_brick_stairs_east_2_data[785];
#define stone_brick_stairs_east_2 ((gfx_sprite_t*)stone_brick_stairs_east_2_data)
#define stone_stairs_east_width 27
#define stone_stairs_east_height 29
#define stone_stairs_east_size 785
extern uint8_t stone_stairs_east_data[785];
#define stone_stairs_east ((gfx_sprite_t*)stone_stairs_east_data)
#define brick_stairs_east_width 27
#define brick_stairs_east_height 29
#define brick_stairs_east_size 785
extern uint8_t brick_stairs_east_data[785];
#define brick_stairs_east ((gfx_sprite_t*)brick_stairs_east_data)
#define stone_brick_stairs_south_2_width 27
#define stone_brick_stairs_south_2_height 29
#define stone_brick_stairs_south_2_size 785
extern uint8_t stone_brick_stairs_south_2_data[785];
#define stone_brick_stairs_south_2 ((gfx_sprite_t*)stone_brick_stairs_south_2_data)
#define brick_width 27
#define brick_height 29
#define brick_size 785
extern uint8_t brick_data[785];
#define brick ((gfx_sprite_t*)brick_data)
#define coal_ore_width 27
#define coal_ore_height 29
#define coal_ore_size 785
extern uint8_t coal_ore_data[785];
#define coal_ore ((gfx_sprite_t*)coal_ore_data)
#define stone_width 27
#define stone_height 29
#define stone_size 785
extern uint8_t stone_data[785];
#define stone ((gfx_sprite_t*)stone_data)
#define dirt_width 27
#define dirt_height 29
#define dirt_size 785
extern uint8_t dirt_data[785];
#define dirt ((gfx_sprite_t*)dirt_data)
#define grass_block_width 27
#define grass_block_height 29
#define grass_block_size 785
extern uint8_t grass_block_data[785];
#define grass_block ((gfx_sprite_t*)grass_block_data)
#define stone_brick_width 27
#define stone_brick_height 29
#define stone_brick_size 785
extern uint8_t stone_brick_data[785];
#define stone_brick ((gfx_sprite_t*)stone_brick_data)
#define stone_brick_2_width 27
#define stone_brick_2_height 29
#define stone_brick_2_size 785
extern uint8_t stone_brick_2_data[785];
#define stone_brick_2 ((gfx_sprite_t*)stone_brick_2_data)
#define oak_log_width 27
#define oak_log_height 29
#define oak_log_size 785
extern uint8_t oak_log_data[785];
#define oak_log ((gfx_sprite_t*)oak_log_data)
#define oak_planks_width 27
#define oak_planks_height 29
#define oak_planks_size 785
extern uint8_t oak_planks_data[785];
#define oak_planks ((gfx_sprite_t*)oak_planks_data)
#define sand_width 27
#define sand_height 29
#define sand_size 785
extern uint8_t sand_data[785];
#define sand ((gfx_sprite_t*)sand_data)
#define gravel_width 27
#define gravel_height 29
#define gravel_size 785
extern uint8_t gravel_data[785];
#define gravel ((gfx_sprite_t*)gravel_data)
#define cobblestone_width 27
#define cobblestone_height 29
#define cobblestone_size 785
extern uint8_t cobblestone_data[785];
#define cobblestone ((gfx_sprite_t*)cobblestone_data)
#define pink_flower_width 27
#define pink_flower_height 29
#define pink_flower_size 785
extern uint8_t pink_flower_data[785];
#define pink_flower ((gfx_sprite_t*)pink_flower_data)
#define torch_width 27
#define torch_height 29
#define torch_size 785
extern uint8_t torch_data[785];
#define torch ((gfx_sprite_t*)torch_data)
#define steven_north_1_width 27
#define steven_north_1_height 43
#define steven_north_1_size 1163
extern uint8_t steven_north_1_data[1163];
#define steven_north_1 ((gfx_sprite_t*)steven_north_1_data)
#define steven_east_1_width 27
#define steven_east_1_height 43
#define steven_east_1_size 1163
extern uint8_t steven_east_1_data[1163];
#define steven_east_1 ((gfx_sprite_t*)steven_east_1_data)
#define steven_south_1_width 27
#define steven_south_1_height 43
#define steven_south_1_size 1163
extern uint8_t steven_south_1_data[1163];
#define steven_south_1 ((gfx_sprite_t*)steven_south_1_data)
#define steven_west_1_width 27
#define steven_west_1_height 43
#define steven_west_1_size 1163
extern uint8_t steven_west_1_data[1163];
#define steven_west_1 ((gfx_sprite_t*)steven_west_1_data)
#define selection_box_width 27
#define selection_box_height 29
#define selection_box_size 785
extern uint8_t selection_box_data[785];
#define selection_box ((gfx_sprite_t*)selection_box_data)
#define shadow_block_25percent_width 27
#define shadow_block_25percent_height 29
#define shadow_block_25percent_size 785
extern uint8_t shadow_block_25percent_data[785];
#define shadow_block_25percent ((gfx_sprite_t*)shadow_block_25percent_data)
#define shadow_block_50percent_width 27
#define shadow_block_50percent_height 29
#define shadow_block_50percent_size 785
extern uint8_t shadow_block_50percent_data[785];
#define shadow_block_50percent ((gfx_sprite_t*)shadow_block_50percent_data)
#define sizeof_logo_gfx_pal 512
extern uint16_t logo_gfx_pal[256];

#endif
