// convpng v6.8
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __logo_gfx__
#define __logo_gfx__
#include <stdint.h>

#define logo_gfx_transparent_color_index 0

#define water_full_width 27
#define water_full_height 29
#define water_full_size 785
extern uint8_t water_full_data[785];
#define water_full ((gfx_sprite_t*)water_full_data)
#define water_surface_width 27
#define water_surface_height 29
#define water_surface_size 785
extern uint8_t water_surface_data[785];
#define water_surface ((gfx_sprite_t*)water_surface_data)
#define lava_full_width 27
#define lava_full_height 29
#define lava_full_size 785
extern uint8_t lava_full_data[785];
#define lava_full ((gfx_sprite_t*)lava_full_data)
#define lava_surface_width 27
#define lava_surface_height 29
#define lava_surface_size 785
extern uint8_t lava_surface_data[785];
#define lava_surface ((gfx_sprite_t*)lava_surface_data)
#define glass_block_width 27
#define glass_block_height 29
#define glass_block_size 785
extern uint8_t glass_block_data[785];
#define glass_block ((gfx_sprite_t*)glass_block_data)
#define glass_pane_west_to_east_width 27
#define glass_pane_west_to_east_height 29
#define glass_pane_west_to_east_size 785
extern uint8_t glass_pane_west_to_east_data[785];
#define glass_pane_west_to_east ((gfx_sprite_t*)glass_pane_west_to_east_data)
#define glass_pane_south_to_north_width 27
#define glass_pane_south_to_north_height 29
#define glass_pane_south_to_north_size 785
extern uint8_t glass_pane_south_to_north_data[785];
#define glass_pane_south_to_north ((gfx_sprite_t*)glass_pane_south_to_north_data)
#define oak_leaves_width 27
#define oak_leaves_height 29
#define oak_leaves_size 785
extern uint8_t oak_leaves_data[785];
#define oak_leaves ((gfx_sprite_t*)oak_leaves_data)
#define stone_stairs_east_width 27
#define stone_stairs_east_height 29
#define stone_stairs_east_size 785
extern uint8_t stone_stairs_east_data[785];
#define stone_stairs_east ((gfx_sprite_t*)stone_stairs_east_data)
#define brick_stairs_east_width 27
#define brick_stairs_east_height 29
#define brick_stairs_east_size 785
extern uint8_t brick_stairs_east_data[785];
#define brick_stairs_east ((gfx_sprite_t*)brick_stairs_east_data)
#define brick_width 27
#define brick_height 29
#define brick_size 785
extern uint8_t brick_data[785];
#define brick ((gfx_sprite_t*)brick_data)
#define coal_ore_width 27
#define coal_ore_height 29
#define coal_ore_size 785
extern uint8_t coal_ore_data[785];
#define coal_ore ((gfx_sprite_t*)coal_ore_data)
#define stone_width 27
#define stone_height 29
#define stone_size 785
extern uint8_t stone_data[785];
#define stone ((gfx_sprite_t*)stone_data)
#define dirt_width 27
#define dirt_height 29
#define dirt_size 785
extern uint8_t dirt_data[785];
#define dirt ((gfx_sprite_t*)dirt_data)
#define grass_block_width 27
#define grass_block_height 29
#define grass_block_size 785
extern uint8_t grass_block_data[785];
#define grass_block ((gfx_sprite_t*)grass_block_data)
#define stone_brick_width 27
#define stone_brick_height 29
#define stone_brick_size 785
extern uint8_t stone_brick_data[785];
#define stone_brick ((gfx_sprite_t*)stone_brick_data)
#define oak_log_width 27
#define oak_log_height 29
#define oak_log_size 785
extern uint8_t oak_log_data[785];
#define oak_log ((gfx_sprite_t*)oak_log_data)
#define oak_planks_width 27
#define oak_planks_height 29
#define oak_planks_size 785
extern uint8_t oak_planks_data[785];
#define oak_planks ((gfx_sprite_t*)oak_planks_data)
#define sand_width 27
#define sand_height 29
#define sand_size 785
extern uint8_t sand_data[785];
#define sand ((gfx_sprite_t*)sand_data)
#define gravel_width 27
#define gravel_height 29
#define gravel_size 785
extern uint8_t gravel_data[785];
#define gravel ((gfx_sprite_t*)gravel_data)
#define cobblestone_width 27
#define cobblestone_height 29
#define cobblestone_size 785
extern uint8_t cobblestone_data[785];
#define cobblestone ((gfx_sprite_t*)cobblestone_data)
#define stone_25p_width 27
#define stone_25p_height 29
#define stone_25p_size 785
extern uint8_t stone_25p_data[785];
#define stone_25p ((gfx_sprite_t*)stone_25p_data)
#define stone_25p_top_width 27
#define stone_25p_top_height 29
#define stone_25p_top_size 785
extern uint8_t stone_25p_top_data[785];
#define stone_25p_top ((gfx_sprite_t*)stone_25p_top_data)
#define stone_25p_right_width 27
#define stone_25p_right_height 29
#define stone_25p_right_size 785
extern uint8_t stone_25p_right_data[785];
#define stone_25p_right ((gfx_sprite_t*)stone_25p_right_data)
#define stone_25p_left_width 27
#define stone_25p_left_height 29
#define stone_25p_left_size 785
extern uint8_t stone_25p_left_data[785];
#define stone_25p_left ((gfx_sprite_t*)stone_25p_left_data)
#define oak_door_south_width 27
#define oak_door_south_height 43
#define oak_door_south_size 1163
extern uint8_t oak_door_south_data[1163];
#define oak_door_south ((gfx_sprite_t*)oak_door_south_data)
#define oak_door_south_bottom_width 27
#define oak_door_south_bottom_height 29
#define oak_door_south_bottom_size 785
extern uint8_t oak_door_south_bottom_data[785];
#define oak_door_south_bottom ((gfx_sprite_t*)oak_door_south_bottom_data)
#define oak_door_south_top_width 27
#define oak_door_south_top_height 29
#define oak_door_south_top_size 785
extern uint8_t oak_door_south_top_data[785];
#define oak_door_south_top ((gfx_sprite_t*)oak_door_south_top_data)
#define oak_door_east_2_width 27
#define oak_door_east_2_height 43
#define oak_door_east_2_size 1163
extern uint8_t oak_door_east_2_data[1163];
#define oak_door_east_2 ((gfx_sprite_t*)oak_door_east_2_data)
#define oak_door_east_2_bottom_width 27
#define oak_door_east_2_bottom_height 29
#define oak_door_east_2_bottom_size 785
extern uint8_t oak_door_east_2_bottom_data[785];
#define oak_door_east_2_bottom ((gfx_sprite_t*)oak_door_east_2_bottom_data)
#define oak_door_east_2_top_width 27
#define oak_door_east_2_top_height 29
#define oak_door_east_2_top_size 785
extern uint8_t oak_door_east_2_top_data[785];
#define oak_door_east_2_top ((gfx_sprite_t*)oak_door_east_2_top_data)
#define ladder_north_width 27
#define ladder_north_height 29
#define ladder_north_size 785
extern uint8_t ladder_north_data[785];
#define ladder_north ((gfx_sprite_t*)ladder_north_data)
#define pink_flower_width 27
#define pink_flower_height 29
#define pink_flower_size 785
extern uint8_t pink_flower_data[785];
#define pink_flower ((gfx_sprite_t*)pink_flower_data)
#define torch_width 27
#define torch_height 29
#define torch_size 785
extern uint8_t torch_data[785];
#define torch ((gfx_sprite_t*)torch_data)
#define steven_north_1_width 27
#define steven_north_1_height 43
#define steven_north_1_size 1163
extern uint8_t steven_north_1_data[1163];
#define steven_north_1 ((gfx_sprite_t*)steven_north_1_data)
#define steven_east_1_width 27
#define steven_east_1_height 43
#define steven_east_1_size 1163
extern uint8_t steven_east_1_data[1163];
#define steven_east_1 ((gfx_sprite_t*)steven_east_1_data)
#define steven_south_1_width 27
#define steven_south_1_height 43
#define steven_south_1_size 1163
extern uint8_t steven_south_1_data[1163];
#define steven_south_1 ((gfx_sprite_t*)steven_south_1_data)
#define steven_west_1_width 27
#define steven_west_1_height 43
#define steven_west_1_size 1163
extern uint8_t steven_west_1_data[1163];
#define steven_west_1 ((gfx_sprite_t*)steven_west_1_data)
#define selection_box_width 27
#define selection_box_height 29
#define selection_box_size 785
extern uint8_t selection_box_data[785];
#define selection_box ((gfx_sprite_t*)selection_box_data)
#define selection_tile_width 27
#define selection_tile_height 29
#define selection_tile_size 785
extern uint8_t selection_tile_data[785];
#define selection_tile ((gfx_sprite_t*)selection_tile_data)
#define shadow_left_12p_width 27
#define shadow_left_12p_height 29
#define shadow_left_12p_size 785
extern uint8_t shadow_left_12p_data[785];
#define shadow_left_12p ((gfx_sprite_t*)shadow_left_12p_data)
#define shadow_left_25p_width 27
#define shadow_left_25p_height 29
#define shadow_left_25p_size 785
extern uint8_t shadow_left_25p_data[785];
#define shadow_left_25p ((gfx_sprite_t*)shadow_left_25p_data)
#define shadow_left_37p_width 27
#define shadow_left_37p_height 29
#define shadow_left_37p_size 785
extern uint8_t shadow_left_37p_data[785];
#define shadow_left_37p ((gfx_sprite_t*)shadow_left_37p_data)
#define shadow_left_50p_width 27
#define shadow_left_50p_height 29
#define shadow_left_50p_size 785
extern uint8_t shadow_left_50p_data[785];
#define shadow_left_50p ((gfx_sprite_t*)shadow_left_50p_data)
#define shadow_left_63p_width 27
#define shadow_left_63p_height 29
#define shadow_left_63p_size 785
extern uint8_t shadow_left_63p_data[785];
#define shadow_left_63p ((gfx_sprite_t*)shadow_left_63p_data)
#define shadow_left_75p_width 27
#define shadow_left_75p_height 29
#define shadow_left_75p_size 785
extern uint8_t shadow_left_75p_data[785];
#define shadow_left_75p ((gfx_sprite_t*)shadow_left_75p_data)
#define shadow_left_88p_width 27
#define shadow_left_88p_height 29
#define shadow_left_88p_size 785
extern uint8_t shadow_left_88p_data[785];
#define shadow_left_88p ((gfx_sprite_t*)shadow_left_88p_data)
#define shadow_left_100p_width 27
#define shadow_left_100p_height 29
#define shadow_left_100p_size 785
extern uint8_t shadow_left_100p_data[785];
#define shadow_left_100p ((gfx_sprite_t*)shadow_left_100p_data)
#define shadow_right_12p_width 27
#define shadow_right_12p_height 29
#define shadow_right_12p_size 785
extern uint8_t shadow_right_12p_data[785];
#define shadow_right_12p ((gfx_sprite_t*)shadow_right_12p_data)
#define shadow_right_25p_width 27
#define shadow_right_25p_height 29
#define shadow_right_25p_size 785
extern uint8_t shadow_right_25p_data[785];
#define shadow_right_25p ((gfx_sprite_t*)shadow_right_25p_data)
#define shadow_right_37p_width 27
#define shadow_right_37p_height 29
#define shadow_right_37p_size 785
extern uint8_t shadow_right_37p_data[785];
#define shadow_right_37p ((gfx_sprite_t*)shadow_right_37p_data)
#define shadow_right_50p_width 27
#define shadow_right_50p_height 29
#define shadow_right_50p_size 785
extern uint8_t shadow_right_50p_data[785];
#define shadow_right_50p ((gfx_sprite_t*)shadow_right_50p_data)
#define shadow_right_63p_width 27
#define shadow_right_63p_height 29
#define shadow_right_63p_size 785
extern uint8_t shadow_right_63p_data[785];
#define shadow_right_63p ((gfx_sprite_t*)shadow_right_63p_data)
#define shadow_right_75p_width 27
#define shadow_right_75p_height 29
#define shadow_right_75p_size 785
extern uint8_t shadow_right_75p_data[785];
#define shadow_right_75p ((gfx_sprite_t*)shadow_right_75p_data)
#define shadow_right_88p_width 27
#define shadow_right_88p_height 29
#define shadow_right_88p_size 785
extern uint8_t shadow_right_88p_data[785];
#define shadow_right_88p ((gfx_sprite_t*)shadow_right_88p_data)
#define shadow_right_100p_width 27
#define shadow_right_100p_height 29
#define shadow_right_100p_size 785
extern uint8_t shadow_right_100p_data[785];
#define shadow_right_100p ((gfx_sprite_t*)shadow_right_100p_data)
#define shadow_floor_12p_width 27
#define shadow_floor_12p_height 29
#define shadow_floor_12p_size 785
extern uint8_t shadow_floor_12p_data[785];
#define shadow_floor_12p ((gfx_sprite_t*)shadow_floor_12p_data)
#define shadow_floor_25p_width 27
#define shadow_floor_25p_height 29
#define shadow_floor_25p_size 785
extern uint8_t shadow_floor_25p_data[785];
#define shadow_floor_25p ((gfx_sprite_t*)shadow_floor_25p_data)
#define shadow_floor_37p_width 27
#define shadow_floor_37p_height 29
#define shadow_floor_37p_size 785
extern uint8_t shadow_floor_37p_data[785];
#define shadow_floor_37p ((gfx_sprite_t*)shadow_floor_37p_data)
#define shadow_floor_50p_width 27
#define shadow_floor_50p_height 29
#define shadow_floor_50p_size 785
extern uint8_t shadow_floor_50p_data[785];
#define shadow_floor_50p ((gfx_sprite_t*)shadow_floor_50p_data)
#define shadow_floor_63p_width 27
#define shadow_floor_63p_height 29
#define shadow_floor_63p_size 785
extern uint8_t shadow_floor_63p_data[785];
#define shadow_floor_63p ((gfx_sprite_t*)shadow_floor_63p_data)
#define shadow_floor_75p_width 27
#define shadow_floor_75p_height 29
#define shadow_floor_75p_size 785
extern uint8_t shadow_floor_75p_data[785];
#define shadow_floor_75p ((gfx_sprite_t*)shadow_floor_75p_data)
#define shadow_floor_88p_width 27
#define shadow_floor_88p_height 29
#define shadow_floor_88p_size 785
extern uint8_t shadow_floor_88p_data[785];
#define shadow_floor_88p ((gfx_sprite_t*)shadow_floor_88p_data)
#define shadow_floor_100p_width 27
#define shadow_floor_100p_height 29
#define shadow_floor_100p_size 785
extern uint8_t shadow_floor_100p_data[785];
#define shadow_floor_100p ((gfx_sprite_t*)shadow_floor_100p_data)
#define fire_1_width 27
#define fire_1_height 29
#define fire_1_size 785
extern uint8_t fire_1_data[785];
#define fire_1 ((gfx_sprite_t*)fire_1_data)
#define fire_2_width 27
#define fire_2_height 29
#define fire_2_size 785
extern uint8_t fire_2_data[785];
#define fire_2 ((gfx_sprite_t*)fire_2_data)
#define fire_3_width 27
#define fire_3_height 29
#define fire_3_size 785
extern uint8_t fire_3_data[785];
#define fire_3 ((gfx_sprite_t*)fire_3_data)
#define fire_4_width 27
#define fire_4_height 29
#define fire_4_size 785
extern uint8_t fire_4_data[785];
#define fire_4 ((gfx_sprite_t*)fire_4_data)
#define fire_5_width 27
#define fire_5_height 29
#define fire_5_size 785
extern uint8_t fire_5_data[785];
#define fire_5 ((gfx_sprite_t*)fire_5_data)
#define fire_6_width 27
#define fire_6_height 29
#define fire_6_size 785
extern uint8_t fire_6_data[785];
#define fire_6 ((gfx_sprite_t*)fire_6_data)
#define fire_7_width 27
#define fire_7_height 29
#define fire_7_size 785
extern uint8_t fire_7_data[785];
#define fire_7 ((gfx_sprite_t*)fire_7_data)
#define fire_8_width 27
#define fire_8_height 29
#define fire_8_size 785
extern uint8_t fire_8_data[785];
#define fire_8 ((gfx_sprite_t*)fire_8_data)
#define fire_9_width 27
#define fire_9_height 29
#define fire_9_size 785
extern uint8_t fire_9_data[785];
#define fire_9 ((gfx_sprite_t*)fire_9_data)
#define fire_10_width 27
#define fire_10_height 29
#define fire_10_size 785
extern uint8_t fire_10_data[785];
#define fire_10 ((gfx_sprite_t*)fire_10_data)
#define fire_11_width 27
#define fire_11_height 29
#define fire_11_size 785
extern uint8_t fire_11_data[785];
#define fire_11 ((gfx_sprite_t*)fire_11_data)
#define fire_12_width 27
#define fire_12_height 29
#define fire_12_size 785
extern uint8_t fire_12_data[785];
#define fire_12 ((gfx_sprite_t*)fire_12_data)
#define fire_13_width 27
#define fire_13_height 29
#define fire_13_size 785
extern uint8_t fire_13_data[785];
#define fire_13 ((gfx_sprite_t*)fire_13_data)
#define fire_14_width 27
#define fire_14_height 29
#define fire_14_size 785
extern uint8_t fire_14_data[785];
#define fire_14 ((gfx_sprite_t*)fire_14_data)
#define fire_15_width 27
#define fire_15_height 29
#define fire_15_size 785
extern uint8_t fire_15_data[785];
#define fire_15 ((gfx_sprite_t*)fire_15_data)
#define fire_16_width 27
#define fire_16_height 29
#define fire_16_size 785
extern uint8_t fire_16_data[785];
#define fire_16 ((gfx_sprite_t*)fire_16_data)
#define chest_1_width 31
#define chest_1_height 43
#define chest_1_size 1335
extern uint8_t chest_1_data[1335];
#define chest_1 ((gfx_sprite_t*)chest_1_data)
#define chest_2_width 31
#define chest_2_height 43
#define chest_2_size 1335
extern uint8_t chest_2_data[1335];
#define chest_2 ((gfx_sprite_t*)chest_2_data)
#define chest_3_width 31
#define chest_3_height 43
#define chest_3_size 1335
extern uint8_t chest_3_data[1335];
#define chest_3 ((gfx_sprite_t*)chest_3_data)
#define chest_4_width 31
#define chest_4_height 43
#define chest_4_size 1335
extern uint8_t chest_4_data[1335];
#define chest_4 ((gfx_sprite_t*)chest_4_data)
#define chest_5_width 31
#define chest_5_height 43
#define chest_5_size 1335
extern uint8_t chest_5_data[1335];
#define chest_5 ((gfx_sprite_t*)chest_5_data)
#define chest_6_width 31
#define chest_6_height 43
#define chest_6_size 1335
extern uint8_t chest_6_data[1335];
#define chest_6 ((gfx_sprite_t*)chest_6_data)
#define chest_7_width 31
#define chest_7_height 43
#define chest_7_size 1335
extern uint8_t chest_7_data[1335];
#define chest_7 ((gfx_sprite_t*)chest_7_data)
#define chest_8_width 31
#define chest_8_height 43
#define chest_8_size 1335
extern uint8_t chest_8_data[1335];
#define chest_8 ((gfx_sprite_t*)chest_8_data)
#define chest_9_width 31
#define chest_9_height 43
#define chest_9_size 1335
extern uint8_t chest_9_data[1335];
#define chest_9 ((gfx_sprite_t*)chest_9_data)
#define chest_10_width 31
#define chest_10_height 43
#define chest_10_size 1335
extern uint8_t chest_10_data[1335];
#define chest_10 ((gfx_sprite_t*)chest_10_data)
#define chest_11_width 31
#define chest_11_height 43
#define chest_11_size 1335
extern uint8_t chest_11_data[1335];
#define chest_11 ((gfx_sprite_t*)chest_11_data)
#define chest_12_width 31
#define chest_12_height 43
#define chest_12_size 1335
extern uint8_t chest_12_data[1335];
#define chest_12 ((gfx_sprite_t*)chest_12_data)
#define chest_13_width 31
#define chest_13_height 43
#define chest_13_size 1335
extern uint8_t chest_13_data[1335];
#define chest_13 ((gfx_sprite_t*)chest_13_data)
#define chest_14_width 31
#define chest_14_height 43
#define chest_14_size 1335
extern uint8_t chest_14_data[1335];
#define chest_14 ((gfx_sprite_t*)chest_14_data)
#define chest_15_width 31
#define chest_15_height 43
#define chest_15_size 1335
extern uint8_t chest_15_data[1335];
#define chest_15 ((gfx_sprite_t*)chest_15_data)
#define chest_16_width 31
#define chest_16_height 43
#define chest_16_size 1335
extern uint8_t chest_16_data[1335];
#define chest_16 ((gfx_sprite_t*)chest_16_data)
#define play_width 162
#define play_height 29
#define play_size 4700
extern uint8_t play_data[4700];
#define play ((gfx_sprite_t*)play_data)
#define options_width 162
#define options_height 29
#define options_size 4700
extern uint8_t options_data[4700];
#define options ((gfx_sprite_t*)options_data)
#define quitgame_width 162
#define quitgame_height 29
#define quitgame_size 4700
extern uint8_t quitgame_data[4700];
#define quitgame ((gfx_sprite_t*)quitgame_data)
#define playhover_width 162
#define playhover_height 29
#define playhover_size 4700
extern uint8_t playhover_data[4700];
#define playhover ((gfx_sprite_t*)playhover_data)
#define optionshover_width 162
#define optionshover_height 29
#define optionshover_size 4700
extern uint8_t optionshover_data[4700];
#define optionshover ((gfx_sprite_t*)optionshover_data)
#define quitgamehover_width 162
#define quitgamehover_height 29
#define quitgamehover_size 4700
extern uint8_t quitgamehover_data[4700];
#define quitgamehover ((gfx_sprite_t*)quitgamehover_data)
#define sizeof_logo_gfx_pal 512
extern uint16_t logo_gfx_pal[256];

#endif
